apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: client
        image: stevincontainer/client
        command: ["python", "client.py"]
      restartPolicy: Never
